# Generated by Django 6.0.7 on 2026-10-02 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0014_alter_smslog_event_type'),
        ('organizations', '0013_loan_product_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReversalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('savings', 'Savings Payment'), ('shares', 'Shares Payment'), ('loan_repayment', 'Loan Repayment')], db_index=True, max_length=30)),
                ('original_payment_id', models.CharField(db_index=True, max_length=100)),
                ('document_or_receipt_no', models.CharField(blank=True, default='', max_length=100)),
                ('amount_reversed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reversal_reason', models.TextField()),
                ('reversed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('snapshot_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of payment details before reversal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reversals', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reversals', to='organizations.organization')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reversals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Reversal Log',
                'verbose_name_plural': 'Payment Reversal Logs',
                'db_table': 'tbl_payment_reversal_logs',
                'ordering': ['-reversed_at'],
            },
        ),
    ]
