# Generated by Django 6.0.7 on 2026-09-08 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0010_cleanup_empty_kra_pin_and_email'),
        ('organizations', '0011_add_loan_finance_savings_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_no', models.CharField(db_index=True, max_length=100)),
                ('savings_type', models.CharField(choices=[('normal', 'Normal'), ('welfare', 'Welfare ksh')], default='normal', max_length=30)),
                ('transaction_type', models.CharField(choices=[('money_in', 'Money In'), ('money_out', 'Money Out')], default='money_in', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='Kenya Shilling(KSH)', max_length=50)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'M-pesa'), ('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque')], default='mpesa', max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('paid_by', models.CharField(blank=True, max_length=200, null=True)),
                ('week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_payments', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_payments', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_savings_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Payment',
                'verbose_name_plural': 'Savings Payments',
                'db_table': 'tbl_savings_payments',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
