# Generated by Django 6.0.7 on 2026-10-02 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_smslog_event_type'),
        ('organizations', '0013_loan_product_permissions'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingspayment',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='savingspayment',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='savingspayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingspayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_savings_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavingsWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_no', models.CharField(blank=True, default='', max_length=50)),
                ('withdrawal_type', models.CharField(choices=[('exit_sacco', 'Exit Sacco'), ('loan_repayment', 'Loan Repayment'), ('saving_refund', 'Saving Refund'), ('excess_savings', 'Excess Savings'), ('partial_withdrawal', 'Partial Withdrawal'), ('other', 'Other')], default='partial_withdrawal', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_withdrawn', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('savings_drawn_from', models.CharField(choices=[('normal', 'Normal Savings'), ('welfare', 'Welfare')], default='normal', max_length=30)),
                ('bank', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mpesa', max_length=30)),
                ('document_code', models.CharField(blank=True, help_text='Transaction reference / cheque no / document code', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_withdrawal', to='savings.savingspayment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_withdrawals', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_withdrawals', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_savings_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Withdrawal',
                'verbose_name_plural': 'Savings Withdrawals',
                'db_table': 'tbl_savings_withdrawals',
                'ordering': ['-date_withdrawn', '-created_at'],
            },
        ),
    ]
