# Generated by Django 6.0.7 on 2026-09-30 09:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0014_alter_smslog_event_type'),
        ('organizations', '0013_loan_product_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDeductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('paid_thro', models.CharField(default='payroll', max_length=50)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='deductions/uploads/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_batches', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Deduction Batch',
                'verbose_name_plural': 'Monthly Deduction Batches',
                'db_table': 'tbl_monthly_deduction_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Appraisal fees, processing, ledger charges, penalties', max_digits=15)),
                ('loan_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loan installment principal component', max_digits=15)),
                ('loan_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loan installment interest component', max_digits=15)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unpaid registration fees', max_digits=15)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), help_text='Mandatory / scheduled monthly savings deposit', max_digits=15)),
                ('shares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly shares capital contribution', max_digits=15)),
                ('others', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Welfare, insurance, or other monthly contributions', max_digits=15)),
                ('total_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all deduction items', max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount remitted / paid for this month', max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining expected balance (total_expected - amount_paid)', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overpaid', 'Overpaid')], db_index=True, default='pending', max_length=20)),
                ('paid_thro', models.CharField(blank=True, help_text='Remittance method e.g. Payroll Checkoff, Bank Transfer, M-Pesa', max_length=50, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_deductions', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_deductions', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Deduction',
                'verbose_name_plural': 'Monthly Deductions',
                'db_table': 'tbl_monthly_deductions',
                'ordering': ['year', 'month', 'member__first_name'],
                'unique_together': {('organization', 'member', 'month', 'year')},
            },
        ),
    ]
