# Generated by Django 6.0.7 on 2026-10-02 07:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deductions', '0001_initial'),
        ('members', '0014_alter_smslog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDeductionItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('raw_employee_no', models.CharField(blank=True, default='', max_length=100)),
                ('raw_employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_total_ded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_loan_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_loan_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_shares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_others', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_surplus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_logs', to='deductions.monthlydeductionbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='deductions.monthlydeduction')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduction_upload_logs', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Deduction Item Log',
                'verbose_name_plural': 'Monthly Deduction Item Logs',
                'db_table': 'tbl_monthly_deduction_item_logs',
                'ordering': ['batch', 'row_number'],
            },
        ),
    ]
