# Generated by Django 6.0.7 on 2026-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_seed_default_loan_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, help_text='BANK | MPESA | CHEQUE | CASH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_reference',
            field=models.CharField(blank=True, help_text='Cheque / M-Pesa / Bank Reference No.', max_length=100, null=True),
        ),
    ]
