# Generated by Django 6.0.7 on 2026-09-10 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_add_loan_officer'),
        ('members', '0012_mpesa_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(db_index=True, help_text='Unique M-Pesa Transaction ID (e.g. UIATRT7PD)', max_length=50, unique=True)),
                ('transaction_type', models.CharField(default='Pay Bill', help_text='e.g. Pay Bill, Customer PayBill', max_length=50)),
                ('trans_time', models.DateTimeField(help_text='Transaction timestamp sent by Safaricom')),
                ('trans_amount', models.DecimalField(decimal_places=2, help_text='Amount received in KES', max_digits=12)),
                ('business_short_code', models.CharField(help_text='Paybill or Till Number (e.g. 673649)', max_length=20)),
                ('bill_ref_number', models.CharField(db_index=True, help_text='Account reference entered by customer (e.g. National ID or Loan #)', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('org_account_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Utility account balance after transaction', max_digits=14, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, default='', max_length=100)),
                ('msisdn', models.CharField(help_text='Customer phone number (e.g. 254712345670)', max_length=30)),
                ('first_name', models.CharField(blank=True, default='', help_text='Sender first name from Safaricom', max_length=100)),
                ('raw_payload', models.JSONField(help_text='Complete JSON payload received from Safaricom callback')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed & Allocated'), ('UNALLOCATED', 'Received (Unallocated)'), ('FAILED', 'Failed / Error')], db_index=True, default='UNALLOCATED', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='loans.loan')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='members.member')),
                ('repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='loans.repayment')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-trans_time', '-created_at'],
            },
        ),
    ]
