# Generated by Django 6.0.7 on 2026-09-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_mpesa_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True if system.royalltd.co.ke verified this transaction'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='unique_serial',
            field=models.CharField(blank=True, db_index=True, help_text='Unique relay batch or payment serial ID from system.royalltd.co.ke', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='verification_response',
            field=models.JSONField(blank=True, help_text='Raw payload returned by verification URL', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='verify_url',
            field=models.CharField(blank=True, help_text='Verification endpoint URL called for confirmation handshake', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed & Allocated'), ('UNALLOCATED', 'Received (Unallocated)'), ('FAILED', 'Failed / Error'), ('VERIFICATION_FAILED', 'Relay Verification Failed')], db_index=True, default='UNALLOCATED', max_length=20),
        ),
    ]
