# Generated by Django 6.0.7 on 2026-09-14 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_mpesa_verification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaReceivedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_serial', models.IntegerField(blank=True, db_index=True, help_text='Source mpesa_transactions id / unique serial', null=True)),
                ('mpesa_payload', models.TextField(blank=True, help_text='Full posted JSON', null=True)),
                ('transID', models.CharField(blank=True, db_index=True, help_text='M-Pesa TransID', max_length=40, null=True)),
                ('verify_url', models.CharField(blank=True, help_text='Source verification URL', max_length=255, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', help_text='Receive status', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Processing or error message', null=True)),
                ('verification_response', models.TextField(blank=True, help_text='Callback verification response', null=True)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp received')),
                ('ipaddress', models.CharField(blank=True, help_text='Client IP address', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Received M-Pesa Payment',
                'verbose_name_plural': 'Received M-Pesa Payments',
                'db_table': 'mpesa_receivedmpesapayments',
                'ordering': ['-createdon'],
            },
        ),
    ]
