# Generated by Django 6.0.7 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_mpesareceivedpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reference_weekly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Algorithmically simulated reference weekly installment', max_digits=15, null=True),
        ),
    ]
