# Generated by Django 6.0.7 on 2026-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loan_reference_weekly_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='document_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='jv_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='jv_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='reference_type',
            field=models.CharField(db_index=True, help_text='DISBURSEMENT | REPAYMENT | FEE | PENALTY | WRITE_OFF | RESCHEDULE | GENERAL_JOURNAL | BROUGHT_FORWARD', max_length=50),
        ),
    ]
