# Generated by Django 6.0.7 on 2026-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_ledgerentry_document_no_ledgerentry_jv_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending_application', 'Pending Application'), ('appraised', 'Appraised'), ('approved', 'Approved'), ('active', 'Active'), ('watchful', 'Watchful (1-30d Overdue)'), ('non_performing', 'Non-Performing (31-90d Overdue)'), ('doubtful', 'Doubtful (91-180d Overdue)'), ('defaulted', 'Defaulted'), ('closed', 'Closed / Fully Paid'), ('written_off', 'Written Off'), ('rejected', 'Rejected')], db_index=True, default='pending_application', max_length=30),
        ),
    ]
