# Generated by Django 6.0.7 on 2026-10-02 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_loan_repayments', to=settings.AUTH_USER_MODEL),
        ),
    ]
