# Generated by Django 6.0.7 on 2026-07-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_member_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_next_of_kin', models.BooleanField(default=True)),
                ('show_vehicle', models.BooleanField(default=True)),
                ('show_guarantor', models.BooleanField(default=True)),
                ('show_kra_pin', models.BooleanField(default=True)),
                ('require_phone', models.BooleanField(default=True)),
                ('require_national_id', models.BooleanField(default=True)),
                ('require_passport_photo', models.BooleanField(default=False)),
                ('require_vehicle', models.BooleanField(default=False)),
                ('require_next_of_kin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Configuration',
                'verbose_name_plural': 'Member Configuration',
                'db_table': 'tbl_member_configuration',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('national_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('physical_address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('registration_stage', models.CharField(choices=[('DATA_CAPTURE_PENDING', 'Data Capture Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active')], db_index=True, default='DATA_CAPTURE_PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.membercategory')),
            ],
            options={
                'db_table': 'tbl_members',
                'ordering': ['first_name', 'other_names'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guarantor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_members', to='members.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='members.member')),
            ],
            options={
                'db_table': 'tbl_guarantors',
                'ordering': ['first_name', 'other_names'],
            },
        ),
        migrations.CreateModel(
            name='MemberAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('CONVERT', 'Convert'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], db_index=True, max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='members.member')),
            ],
            options={
                'db_table': 'tbl_member_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(blank=True, max_length=50)),
                ('current_stage', models.CharField(db_index=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_history', to='members.member')),
            ],
            options={
                'db_table': 'tbl_member_workflow_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('physical_address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='members.member')),
            ],
            options={
                'db_table': 'tbl_next_of_kin',
                'ordering': ['first_name', 'other_names'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('chassis_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='members.member')),
            ],
            options={
                'db_table': 'tbl_vehicles',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configurations', to='members.membercategory')),
            ],
            options={
                'db_table': 'tbl_field_configuration',
                'ordering': ['category', 'display_order'],
                'constraints': [models.UniqueConstraint(fields=('category', 'field_name'), name='unique_category_field')],
            },
        ),
    ]
