# Generated by Django 6.0.7 on 2026-07-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_backfill_member_organization'),
        ('organizations', '0005_bootstrap_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organizations.organization'),
        ),
    ]
