# Generated by Django 6.0.7 on 2026-07-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaudit',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('COMPLETE_REGISTRATION', 'Complete Registration'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate')], db_index=True, max_length=30),
        ),
    ]
