# Generated by Django 6.0.7 on 2026-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_activated_at_member_activated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='other_names',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
