# Generated by Django Migration for SMSLog model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_other_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('event_type', models.CharField(
                    choices=[
                        ('bulk_broadcast', 'Bulk Broadcast'),
                        ('loan_application', 'Loan Application'),
                        ('loan_approval', 'Loan Approval'),
                        ('loan_disbursement', 'Loan Disbursement'),
                        ('repayment_confirmation', 'Repayment Confirmation'),
                        ('overdue_alert', 'Overdue Delinquency Alert'),
                        ('loan_completion', 'Loan Completion'),
                        ('welcome', 'Welcome Registration'),
                        ('general', 'General Notification'),
                    ],
                    db_index=True,
                    default='bulk_broadcast',
                    max_length=50,
                )),
                ('status', models.CharField(
                    choices=[
                        ('sent', 'Sent'),
                        ('failed', 'Failed'),
                        ('pending', 'Pending'),
                    ],
                    db_index=True,
                    default='sent',
                    max_length=20,
                )),
                ('error_message', models.TextField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('member', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sms_logs',
                    to='members.member',
                )),
            ],
            options={
                'verbose_name': 'SMS Delivery Log',
                'verbose_name_plural': 'SMS Delivery Logs',
                'db_table': 'tbl_sms_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
