# Generated by Django 6.0.7 on 2026-09-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_other_members_to_other_guarantors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='event_type',
            field=models.CharField(choices=[('bulk_broadcast', 'Bulk Broadcast'), ('loan_application', 'Loan Application'), ('loan_approval', 'Loan Approval'), ('loan_disbursement', 'Loan Disbursement'), ('repayment_confirmation', 'Repayment Confirmation'), ('due_date_reminder', 'Due Date Reminder'), ('overdue_alert', 'Overdue Delinquency Alert'), ('loan_completion', 'Loan Completion'), ('welcome', 'Welcome Registration'), ('general', 'General Notification')], db_index=True, default='bulk_broadcast', max_length=50),
        ),
    ]
