# Generated by Django 6.0.7 on 2026-10-02 08:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_smslog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initial_savings_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial savings deposit submitted at registration', max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='initial_shares_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial share capital contribution submitted at registration', max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_channel',
            field=models.CharField(blank=True, default='', help_text='Payment mode used if paid upfront (e.g. MPESA, BANK, CASH, DEDUCTION)', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Transaction code or receipt reference for upfront registration payment', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Standard or customized registration fee for the member', max_digits=12),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_fee_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the one-time registration fee was paid upfront at registration'),
        ),
    ]
