# Generated by Django 6.0.7 on 2026-10-02 09:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_initial_savings_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaudit',
            name='new_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='memberaudit',
            name='old_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
