# Generated by Django 6.0.7 on 2026-09-17 10:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0013_alter_smslog_event_type'),
        ('organizations', '0011_add_loan_finance_savings_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_no', models.CharField(db_index=True, max_length=100)),
                ('share_type', models.CharField(choices=[('ordinary', 'Ordinary Shares'), ('preference', 'Preference Shares'), ('capital', 'Capital Shares')], default='ordinary', max_length=30)),
                ('number_of_shares', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('share_price', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='Kenya Shilling(KSH)', max_length=50)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'M-pesa'), ('cash', 'Cash'), ('bank', 'Bank'), ('cheque', 'Cheque')], default='mpesa', max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('paid_on', models.DateField(default=django.utils.timezone.now)),
                ('paid_by', models.CharField(blank=True, max_length=200, null=True)),
                ('week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_payments', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_payments', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_share_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Payment',
                'verbose_name_plural': 'Share Payments',
                'db_table': 'tbl_share_payments',
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
