# Generated by Django 6.0.7 on 2026-10-02 07:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_smslog_event_type'),
        ('organizations', '0013_loan_product_permissions'),
        ('shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepayment',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sharepayment',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sharepayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharepayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_share_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShareTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_type', models.CharField(choices=[('ordinary', 'Ordinary Shares'), ('preference', 'Preference Shares'), ('capital', 'Capital Shares')], default='ordinary', max_length=30)),
                ('number_of_shares', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shares_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Price per share', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_transferred', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_out_shares', to='members.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transfers', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_share_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_member', models.ForeignKey(blank=True, help_text='Recipient member, or null if redeemed / transferred to SACCO pool', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_in_shares', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Transfer',
                'verbose_name_plural': 'Share Transfers',
                'db_table': 'tbl_share_transfers',
                'ordering': ['-date_transferred', '-created_at'],
            },
        ),
    ]
