# Generated by Django 6.0.7 on 2026-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_bootstrap_rbac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module', 'name']},
        ),
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
