# Generated by Django 6.0.7 on 2026-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_populate_permission_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
